char * nextToken(char ** tokenString);
char * handleCommand(char * request);
void move(int amount);
void shift(char * directionString);
void addMark(char * markName);
void jump(char * markName);
void layout(char * l);
void zoom(int level);
void focus(char * argA, char * argB);
void containerize(void);
void kill(void);
